### ISSUE TITLE
allShortestPaths

### ISSUE THREAD

**Issue by maxtepkeev** [neo4j-contrib/neomodel#130]
Hi!

Thanks for the great package!

I'm trying to get allShortestPaths between two nodes with the following cypher query:

``` python
results, _ = db.cypher_query(
    "MATCH "
    "(from:Point {system_name: 'Point1'}), "
    "(to:Point {system_name: 'Point10'}), "
    "p = allShortestPaths(from-[:NEXT|CONNECTS_WITH*..100]-to) RETURN p"
)
print([Point.inflate(row[0]) for row in results])
```

During `db.cypher_query` execution the following exception is raised:

```
Traceback (most recent call last):
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/neomodel/util.py", line 195, in cypher_query
    results = self._execute_query(query, params)
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/neomodel/util.py", line 189, in _execute_query
    result = neo4j.CypherResults(cq._cypher._post({'query': query, 'params': params or {}}))
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/py2neo/neo4j.py", line 1139, in __init__
    for row in content["data"]
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/py2neo/neo4j.py", line 1139, in <listcomp>
    for row in content["data"]
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/neomodel/util.py", line 77, in _hydrated
    return type(data)([_hydrated(datum) for datum in data])
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/neomodel/util.py", line 77, in <listcomp>
    return type(data)([_hydrated(datum) for datum in data])
  File "/usr/local/projects/neo4j/python/lib/python3.4/site-packages/neomodel/util.py", line 75, in _hydrated
    raise NotImplemented("Don't know how to inflate: " + repr(data))
TypeError: 'NotImplementedType' object is not callable
```

Am I doing something wrong ?

**Comment by aanastasiou** [comment]
@maxtepkeev, @richardschwab 

This is an interesting feature for a number of reasons but while it is impossible to do exactly what you are after at the moment, writing a response for it made me realise a short and long term improvement we could have in neomodel.

So, the situation is this: Indeed, at the moment we are not resolving the `Path` data type which is what the Neo4j driver would return from the database for the sort of queries you indicate there. So:

1. In the short term, you will be able to "unroll" the `Path`'s `relationships` with the addition of something like `return extract(rel in relationships(p)|rel)`. If you perform a `neomodel.db.cypher_query` with `resolve_objects = True`, this will return a list of your data model's relationship classes which naturally have their start and end nodes at their `start_node, end_node` attributes.  This will be available after finalising [this PR](https://github.com/neo4j-contrib/neomodel/pull/421).
    * Also in the short term, I have been in the position where I had to return `allShortestPaths` results and I realised that I did not need all of the data from the path. I was able to return specific properties from the nodes and relationships of the path (again, via a `cypher_query`) which was enough for my use case.

2. In the long term, it will be possible to resolve the `Path` data type. This is not too difficult, but in that case, the `Path` could present itself to the user as a starting Node. Anything contained in the `Path` would be readily available (because it has travelled from the db to the client) and anything else required would have to be fetched from the dbms with a request (e.g. upon hitting a node, a `refresh()` could be performed at will, to ensure that the `Node` is fully loaded from the db.).

Hope this helps.

**Comment by aanastasiou** [comment]
@mariusconjeaud , @maxtepkeev Yes, I just tried this and it should work from 5.1.1 owards.
