### ISSUE TITLE
Don't pin version of neo4j-driver 

### ISSUE THREAD

**Issue by mjmare** [neo4j-contrib/neomodel#290]
Setup.py currently specifies 1.5.2 which does not exist (anymore?), so it drops down to 1.2.1. I'd rather use 1.5.3.
PS I understand there may be circumstances where you do want to pin the version.

**Comment by robertlagrant** [comment]
This is causing a problem - currently the neo4j-python-driver is pinned to <1.7.0, which has a big bug:

https://github.com/neo4j/neo4j-python-driver/blob/4d7d898d4dcd5240e74af66c0e04dd6cc5730af4/neo4j/v1/types/temporal.py#L112 passes an integer into a function that immediately `asserts` that value is a Date. This is only fixed in 1.7.x, rather than a 1.6.x bugfix.

Is there a reason for the pin? It literally throws an AssertionError if you take the wrong path down the code.

**Comment by aanastasiou** [comment]
@robertlagrant Thank you very much for bringing this under our attention. The only reason for the pin is to ensure that `neomodel` works with the specific structure of the driver's module.

This is one of those things [we would like to improve](https://github.com/neo4j-contrib/neomodel/wiki/TODOs-&-Enhancements#infrastructure--framework) in the short term.

If you have an idea about how to deal with this *properly* in the short term, please go ahead and submit a PR. 

I would look into the highest version of the driver that works with minimal changes to the current source and pin it to that one. If larger changes are required to bring the code up to date with the latest version (of the driver), then I would be more inclined to incorporate them along with other "big" changes in a major release.

What do you think?

**Comment by robertlagrant** [comment]
@aanastasiou that sounds pretty reasonable!

One thing - having had a look (and made an attempt at the code change - https://github.com/neo4j-contrib/neomodel/pull/432) the neo4j-python-driver upgrade mostly looks like a refactor where it moves logic into the neobolt library, so I wouldn't definitively say that it should be a major version upgrade for neomodel. 

But maybe have a look and see what you think?

**Comment by aanastasiou** [comment]
@robertlagrant Thanks for letting me know, I have not had much desk time these last few days, will take a look and let you know. All the best.
