### ISSUE TITLE
Make StringProperty choices parameter callable to enable dynamic lookups

### ISSUE THREAD

**Issue by mjmare** [neo4j-contrib/neomodel#291]
Currently the choices parameter accepts a static list of tuples. It would be nice if one could specify a function that provides a list of tuples. This enables dynamically looking up the list of allowed values. For example the function could do a query in the database to get the allowed values.

**Comment by aanastasiou** [comment]
The ultimate purpose of `choices` is validation. The point is to constraint the possible values that an attribute can take.

It could well be that these choices are dynamic. But where would this leave batch operations? Would this mean triggering one additional query for every db operation to ensure that the attribute takes the (currently) valid value?

I wonder if this is something that can be addressed with a change in the model. That is, turn the attribute into an entity and attempt to establish a relationship with one of the **existing** nodes. 

If I am way off the mark here, please provide a longer description so that we can see if we could turn this into a feature (?).

**Comment by mjmare** [comment]
I think that providing a callable instead of a list of tuples gives a lot of flexibility. What the callable does to return its values is up to the programmer. Of course if one puts queries or other expensive calls in the callable that might impact performance negatively. Of course the negative effects could be mitigated by caching of some sort. But again, that is the responsibility of the user.  
The neomodel field would only have  to test whether choices is a list or a callable. So minimal impact but a lot of flexibility.

**Comment by aanastasiou** [comment]
@mjmare Alright, I would mark this as an "enhancement" at the moment but I think that it would be best if ause-case scenario was provided for this to see where it fits within the bigger picture.

What do you think?

**Comment by mjmare** [comment]
Hi @aanastasiou, I wouldn't know what to add beyond what I've written above. 
The callable would get its values from elsewhere (config file, query, calculated) created a dynamic list of choices. The dynamic list might be exposed to the user in select fields. The user selects a value, which is sent to the server, where a node is validated by neomodel (by using the callable).

**Comment by aanastasiou** [comment]
@mjmare I am sorry I am picking this up so late. I see what you mean. This has been added to the Wiki already.

**Comment by mjmare** [comment]
No prob, I appreciate your efforts!
