### ISSUE TITLE
neomodel.exception.DeflateError thrown when I try to filter by a partial email

### ISSUE THREAD

**Issue by mcniac** [neo4j-contrib/neomodel#324]
I have a node that has an email property. when I try to filter with icontains I get this error

    class Person(StructuredNode):
        name = StringProperty()
        email = EmailProperty()

    items = Person.nodes.filter(email__icontains='gmail')

this throws this error

    ValueError: 'gmail' does not matches '[^@]+@[^@]+\\.[^@]+'
    During handling of the above exception, another exception occurred:
    DeflateError

**Comment by aanastasiou** [comment]
Hi @mcniac 

You have probably resolved this by now but I thought I would provide a response even if it is to close this issue.

What you are experiencing is predictable since all `Property` describe the **type** that a _value_ must conform with.

What would work in this case is:

```
items = Person.nodes.filter(email__regex = '.*\@gmail.*')
```

Hope this helps.
