### ISSUE TITLE
Django Rest Framework Serializer or any other serializer for neomodel

### ISSUE THREAD

**Issue by prabin525** [neo4j-contrib/neomodel#342]
I am new to neomodel but have been working with drf for a long time. Is there a way to use the drf serializer in neomodel or is there any other way around. How can i serialize the neomodel objects.

**Comment by prabin525** [comment]
@hustzoujia I don't think it is possible to use the DRF serializer. I researched and couldn't find a work around, so I serialized them on my own. Every model has a properties method which gives all the properties of that model in a dictionary. I used that to serialize the objects in a view on my own.

**Comment by hustzoujia** [comment]
thx for your answer :)

2018-06-19 14:57 GMT+08:00 prabin525 <notifications@github.com>:

**Comment by aanastasiou** [comment]
@prabin525 Neomodel is there exactly to provide serialisation for Node and Edge objects to a Neo4J backend. What you probably need is a an [adapter](https://en.wikipedia.org/wiki/Adapter_pattern) or to specialise a DRF Serialiser through a [StructuredNode](http://neomodel.readthedocs.io/en/latest/getting_started.html) (?)

**Comment by HashRocketSyntax** [comment]
@prabin525 care to share a snippet of the serialization? I am old to neomodel, but new to DRF... refactoring =)

**Comment by HashRocketSyntax** [comment]
It looks like the attributes of the DjangoNode model type need to be altered in some way...

...so that it can work with this line of this code that is being used by the serializer of the model that you are abstracting...
`opts = model._meta.concrete_model._meta`

...from this file.
https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/model_meta.py
