### ISSUE TITLE
Problem with 'Overriding the StructuredNode constructor'

### ISSUE THREAD

**Issue by yixiao5428** [neo4j-contrib/neomodel#373]
Hi there,

I'm getting this error when trying to override the StructuredNode constructor, while it is almost exact same code from the doc.

```
Traceback (most recent call last):
  File "/Users/xiao/PycharmProjects/Fooga_New/test/tmp.py", line 48, in <module>
    tmp_node = Item(test='test_test_test')
  File "/Users/xiao/PycharmProjects/Fooga_New/test/tmp.py", line 45, in __init__
    super(Item, self).__init__(self, *args, **kwargs)
  File "/Users/xiao/PycharmProjects/python3_venv/lib/python3.6/site-packages/neomodel/core.py", line 203, in __init__
    super(StructuredNode, self).__init__(*args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```
Here's my code:
```python
from neomodel import db, StructuredNode, StringProperty

db.set_connection('bolt://' + 'neo4j' + ':' + '5428' + '@' + '192.168.0.24' + ':' + '7687')


class Item(StructuredNode):
    name = StringProperty(unique_index=True)
    uid = StringProperty(unique_index=True)

    def __init__(self, test, *args, **kwargs):
        # self.product = product
        kwargs["uid"] = 'g.' + str(test)
        kwargs["name"] = test

        super(Item, self).__init__(self, *args, **kwargs)


tmp_node = Item(test='test_test_test')
tmp_node.save()
```
I'm wondering if I'm using this right?

Thanks.

**Comment by aanastasiou** [comment]
Hello there

Do you have something more specific in mind to do, right after you are performing this kind of initialisation or did you just feel that this is the way to do it?

The short answer is that what you are trying to do there is the default behaviour of `StructuredNode`. So, even if you just leave the definition of class `Item` with its two attributes `name` and `uid` without any additional specification of `__init__`, the default constructor will take the keyword arguments and assign them to attribute values. I think that what the [documentation](https://neomodel.readthedocs.io/en/latest/extending.html#overriding-the-structurednode-constructor) example is trying to highlight there is that:

1. It is necessary to call `super()`
2. It is generally a good idea to include `**kwargs` when overriding, due to the way initialisation takes place.

When you call the `super().__init__()` of `Item`, you don't have to fiddle with the keyword argument dictionary, just go ahead and `name=test` at the parameters (Perhaps that could have been written in a more elegant way in the doc). Also, do you require a `uid` there? Because there is a [property just for that](https://neomodel.readthedocs.io/en/latest/module_documentation.html#neomodel.properties.UniqueIdProperty) and it does not require any parameters.

Hope this helps.

All the best
