### ISSUE TITLE
I seem to be unable to write/persist the data when running. No errors are thrown then checking my neo4j instance after there are no nodes in it. 

### ISSUE THREAD

**Issue by vlurgio** [neo4j-contrib/neomodel#376]
This is an example of how I'm writing.
``` python
@db.write_transaction
def create_node(node):
    """create a node and return it's id
    
    Arguments:
        node {str} -- wiki ID of object
    
    Returns:
        ID -- neo4j ID of newly created node
    """
    if not node["id"] in nodes:
        try:
            _typeT = nlp(node["labels"]["en"])
        except:
            _typeT = None
        temp = Entity(id=node["id"], _type=_typeT).save()
        nodes[node["id"]] = temp
```

**Comment by aanastasiou** [comment]
Can you please provide a little bit more information about the problem you are facing? What and where is `nodes` defined for example, what is the definition of `Entity`? What is the state of the server (What is returned if you were to do a `:schema`?

In general, it would be a good idea to avoid using `id` in your derived classes, as you can see [here](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/core.py#L515), for neomodel, the fact that a node appears to **already have** an `id`, means that the node has been saved and it schedules the node for an `update` rather than a `save()`

**Comment by vlurgio** [comment]
Ah that could've been the issue. I ended up just moving to db.cypher_query() and writing the cypher myself for everything. I think this worked better in my case cause the graph was huge and creating an object for each node would've used memory I didn't have. I stepped through the code and didn't see the id part though good catch thank you.

**Comment by aanastasiou** [comment]
No worries. If you have time at some point, perhaps send a little bit more information about what you are trying to do and we could see if there is anything that could be taken into account in future versions (?).

All the best.
