### ISSUE TITLE
Object Resolution raises ModelDefinitionMismatch for nodes with multiple Labels

### ISSUE THREAD

**Issue by lalitpatel** [neo4j-contrib/neomodel#411]
[Object Resolution](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/util.py#L141) raises `ModelDefinitionMismatch` for nodes with multiple Labels. Is it intentional? 

The following code:
```python
from neomodel import IntegerProperty, StructuredNode, config

config.DATABASE_URL = 'bolt://neo4j:test@localhost:7687' 

class BaseUser(StructuredNode):
    user_id = IntegerProperty(unique_index=True)

class PowerUser(BaseUser):
    pass

class ActiveUser(BaseUser):
    pass

power_user = PowerUser.get_or_create({"user_id": 1})[0]
power_user.cypher("MATCH (n) WHERE id(n)={self} SET n:ActiveUser")
BaseUser.nodes.get(user_id=1)
```

Raises 
```python
ModelDefinitionMismatch: Node with labels PowerUser,ActiveUser,BaseUser does not resolve to any of the known objects
{frozenset(['BaseUser']): <class '__main__.BaseUser'>, frozenset(['ActiveUser', 'BaseUser']): <class '__main__.ActiveUser'>, frozenset(['PowerUser', 'BaseUser']): <class '__main__.PowerUser'>}
```

```ModelDefinitionMismatch                   Traceback (most recent call last)
<ipython-input-2-09776d729518> in <module>()
     14 power_user = PowerUser.get_or_create({"user_id": 1})[0]
     15 power_user.cypher("MATCH (n) WHERE id(n)={self} SET n:ActiveUser")
---> 16 BaseUser.nodes.get(user_id=1)

/Users/lalit/venv/lib/python2.7/site-packages/neomodel/util.pyc in _object_resolution(self, result_list)
    175                     # in a KeyError in the internal dictionary used for resolution. If it is impossible
    176                     # to match, then raise an exception with more details about the error.
--> 177                     raise ModelDefinitionMismatch(a_result_attribute[1], self._NODE_CLASS_REGISTRY)
    178
    179         return result_list
```

**Comment by lalitpatel** [comment]
Ideally all object aware (nodes.get / nodes.filter) cypher queries should try to inflate the node into an instance of type same as the calling object. In the above example it should try to inflate it to an object of class `BaseUser`

**Comment by aanastasiou** [comment]
This is perfectly valid and intentional behaviour.

The key question to ask here is "What is the meaning of a Node having that particular set of labels?".

The whole point of [this mechanism](https://github.com/aanastasiou/neomodelInheritanceTest) is to be able to get a Neo4J Python Driver `Node` object, inspect its labels and instantiate a `neomodel` supported application-specific object. This is slightly more complicated than it sounds when you consider inheritance.

A `Node` with labels `PowerUser,BaseUser` resolves to `PowerUser`.
A `Node` with labels `ActiveUser, BaseUser` resolves to `ActiveUser`.

Which object should a `Node` with labels `PowerUser, ActiveUser, BaseUser` resolve to? And why should that be `BaseUser`?
