### ISSUE TITLE
Inheritance and Custom constructors

### ISSUE THREAD

**Issue by MarcoLotz** [neo4j-contrib/neomodel#416]
Hi all,

the documentation is a bit vague about how to do define your own constructor when inheritance is being performed. The documentation is here: https://neomodel.readthedocs.io/en/latest/extending.html

The example given is:
```python3
class Item(StructuredNode):
    name = StringProperty(unique_index=True)
    uid = StringProperty(unique_index=True)

    def __init__(self, product, *args, **kwargs):
        self.product = product
        kwargs["uid"] = 'g.' + str(self.product.pk)
        kwargs["name"] = self.product.product_name

        super(Item, self).__init__(self, *args, **kwargs)
```

that *just doesnt work* - you can run this yourself and realise that you will get an exception on StructuredNode constructor.

One can make it work with the following:

```python3
class Item(StructuredNode):
    name = StringProperty(unique_index=True)
    uid = StringProperty(unique_index=True)

    def __init__(self, product, *args, **kwargs):
        self.product = product
        kwargs["uid"] = 'g.' + str(self.product.pk)
        kwargs["name"] = self.product.product_name

        super(Item, self).__init__(*args, **kwargs)
```

Still, there's a problem when the .save() method is being called on that object. This happens because it tries to inflate an object using this constructor, without "product" argument being provided.

a solution would be:

```python3
class Item(StructuredNode):
    name = StringProperty(unique_index=True)
    uid = StringProperty(unique_index=True)

    def __init__(self, product = None, *args, **kwargs):
        if product is not None:
            self.product = product
            kwargs["uid"] = 'g.' + str(self.product.pk)
            kwargs["name"] = self.product.product_name

        super(Item, self).__init__(*args, **kwargs)
```

Which is quite ugly and I believe that probably not the intended implementation. How is the correct way to perform it? I can improve the docs on that if required.

**Comment by aanastasiou** [comment]
Would it be possible to talk a little bit more about the model you are trying to build and in which version of Python? (For example, `product` does not appear as an attribute of `Item` (?) in the provided example.)

In general, in a typical scenario like:

```
class BaseItem(neomodel.StructuredNode):
    uid = neomodel.UniqueIdProperty()
    label = neomodel.StringProperty()
    description = neomodel.StringProperty() 

class SpecialItem(BaseItem):
    item_type = neomodel.StringProperty(choices={"F_BLACK":"Black", "F_WHITE", "White"})
```

You don't need to add any special instantiation code.

Where you do need to override `__init__` is in cases where the object itself is basically a `neomodel.StructuredNode` (so that you get the serialisation options) **AND** has some functionality that depends on the domain (e.g. A `SpecialItem` may have some methods that require it a specific variable to be setup at instantiation).

In that case you have a number of options (and this is where the Python version comes in too) but this is not exactly `neomodel` territory. So you could extend the objects that are `StructuredNode` descendants to add the functionality you are after (straightforward), or you could write that functionality spearately and bring the two together via mixins or straight inheritance.

In Python 3, we are relatively lucky to be able to `def __init__(self, some_variable, some_other_variable=None, *args, **kwargs)` which does not require any special way of handling keyword and positional arguments.

As far as `neomodel` is concerned, the only "guideline" around this would be to either always leave an `*args, **kwargs` in your `__init__` (because these are used to instantiate the object via inflate) *or* take some time to properly "filter" the keyword arguments that would have to be sent to the base constructor and those that are to be sent to the concrete constructor, take care of the possible order the arguments might be provided etc.

Hope this helps.

**Comment by MarcoLotz** [comment]
Hi @aanastasiou, I am using Python 3.7.1. The provided example is the very same one in the documentation of neomodel. I literally copied and pasted the code from there. Did you manage to run the example provided in the documentation?

I do understand that the override on the constructor is based on business logic modelling that is not serialized to the data base. I also mentioning that, based on the example provided on the documentation, the constructor should have a default assignment to the non-neo4j-serializable parameters.

**Comment by aanastasiou** [comment]
@MarcoLotz I think that I may have misinterpreted your question. If you are not looking for advice on a specific problem you are dealing with and you are simply highlighting an issue with the documentation then you are welcome to provide a PR about it.

**Comment by MarcoLotz** [comment]
@aanastasiou Thanks for the fast answer. No problem! Indeed that was my point, as probably was [here](https://github.com/neo4j-contrib/neomodel/issues/373). My only question was, is there a better way to do it aside from the way I done - so that documentation is up-to-date?

**Comment by aanastasiou** [comment]
@MarcoLotz Without wanting to go around in circles, it would be best if the question was accompanied by a specific use case scenario. So, my original question on what are you trying to model still holds (we'll come back to that).

I think that the person who contributed that part in the documentation did it from a certain viewpoint. While I did review part of that documentation a few months ago and applied some changes, I did it more for editing reasons (spelling, language, etc) assuming that the example is a valid one.

What I would say about this is that any edits should be made with the objective in mind (e.g. "extending `StructuredNode` classes") and provde as short as possible illustrative examples. But what we can do is this: You can have a go at editing that part of the documentation as you see fit and then I (or anyone else) could contribute further to it to make sure that it is as informative as possible. 

At the moment, what I can see is that an `Item` is attempted to be initialised by an object of type `Product` (?). So, an alternative would be to either look into `kwargs` for `product` and if it exists initialise in one way otherwise initialise in another way **or** check `args[0]` for something of type `Product` and if it exists initialise in a specific way. **BUT**, in many cases of `neomodel` usage, the way you choose to model certain things comes into play too. Why initialise an `Item` via `Product` anyway? You can still do `my_item = Item(name=product_object.product_name).save()` and not occupy yourself with writing a special constructor. What is the role of `Item` and `Product`? A copy constructor for `Item` makes sense, but what is the meaning of initialising via `Product`? 

From my point of view, it is more important to mention there that `*args, **kwargs` should be preserved than demonstrate a specific way of initialising the object.

But, please, by all means, provide a PR and then we work on something more specific (?).

All the best

**Comment by aanastasiou** [comment]
@MarcoLotz [What do you think?](https://github.com/neo4j-contrib/neomodel/pull/442/commits/2903144ae6b385c29bee88d29aec1b08f15f658f#diff-bb8536e1c99720a39c6eaab31dd25385)
