### ISSUE TITLE
BUG: Object Resolution raises ModelDefintionMismatch on nodes with extra labels

### ISSUE THREAD

**Issue by henryfjordan** [neo4j-contrib/neomodel#422]
We have some node classes that we use extra labels to describe/query. Because of the new Object Resolution feature, querying for these nodes now breaks our application.

A good example would be an `archived` label. We have some Node that we might want to soft-delete by adding the `:Archived` label then doing a `MATCH (n) WHERE NOT n:Archived` to get still valid nodes. We use labels because they are more performant than properties for this task.

The problem for us lies in the following code in `_object_resolution()`:

```python
try:
    # Primitive types should remain primitive types, 
    #  Nodes to be resolved to native objects
    resolved_object = a_result_attribute[1]
    
    if type(a_result_attribute[1]) is Node:
        resolved_object = self._NODE_CLASS_REGISTRY[frozenset(a_result_attribute[1].labels)].inflate(
            a_result_attribute[1])
        
    if type(a_result_attribute[1]) is list:
        resolved_object = self._object_resolution([a_result_attribute[1]])                    
    
    result_list[a_result_item[0]][a_result_attribute[0]] = resolved_object
    
except KeyError:
    # Not being able to match the label set of a node with a known object results 
    # in a KeyError in the internal dictionary used for resolution. If it is impossible 
    # to match, then raise an exception with more details about the error.
    raise ModelDefinitionMismatch(a_result_attribute[1], self._NODE_CLASS_REGISTRY)
```
https://github.com/neo4j-contrib/neomodel/blob/8d02b4a0d15a980ec2ac2653846fd01727384638/neomodel/util.py#L165

This code should be checking for the best match, not an exact match. If a node has 7 Labels, including all 5 required for a certain class, the presence of 2 extra labels shouldn't break our queries. I'm not sure exactly how I would implement this in a performant way, but I know raising an error is very limiting in the use-cases this library supports.

Alternatively, we might be able to build a class to describe every single combination of Labels that is possible in our application, but I consider the need to do that in order to upgrade a breaking change and should have triggered a major version change on this library.

Please let me know how I can help resolve this issue without breaking our use-case.

**Comment by henryfjordan** [comment]
Here is a branch with what I think is a fix

https://github.com/neo4j-contrib/neomodel/compare/master...henryfjordan:fix-object-resolution

**Comment by aanastasiou** [comment]
@henryfjordan I can see the inconvenience but at the same time we are going to have to try and balance a few things here.

My immediate response would be to model `archived` as a property. Conceptually, labels are not supposed to be serving the purpose of a boolean property. I would be very surprised if an indexed property was slower than a label lookup. Behind the scenes they are probably using the same indexing algorithm for fast lookups. I think that, at least personally, I am going to have to run a quick check on that.

But just for issue 422, let's say that we cannot do otherwise and we have to make this work.

>This code should be checking for the best match, not an exact match. If a node has 7 Labels, including all 5 required for a certain class, the presence of 2 extra labels shouldn't break our queries.

I do not feel that this is a good idea because from the point of view of the OGM, the only thing it uses to decide which class to instantiate is the set of labels. The OGM does not run a "return all unique labels" filter on the DB to then decide on the best matches based on what it can expect to receive. It does not have full knowledge of the instances, all it has is full knowledge of the "blueprints" for the instances. The OGM receives a `Node` or `Relationship`, examines its labels (or type) and instantiates the right object from the data model. If an exact match is not found, it opts to throw an error rather than do an approximate matching because from the point of view of the OGM a node **might** be existing that makes the appropriate use of a **subset** of the labels from an approximate match. In other words, an `archived` structured node class may exist too (or be created in the future) with a similar lineage that would cause a conflict. The other reason of course is performance. Object resolution at the moment is a straightforward lookup. With approximate matching, you have to first assess the closest match and then retrieve it.


This functionality can be offered however in an alternative way:

1. Prefix the labels that `neomodel` attaches to a class with something like `NMDF_` (or something like that)

2. Have `neomodel` to be using only those labels for its [intended purpose](https://en.wikipedia.org/wiki/Model-driven_engineering).

This would allow you to attach any other labels you like and use them in CYPHER queries.

Just like you, this is an initial thought and I might be missing a reason why this would create even more problems, so I would have to test this at some point.

But this is what I would see as a more viable way forward if we absolutely must can't do otherwise have to support this use-case exactly as described here.

What do you think?

**Comment by henryfjordan** [comment]
There are some scenarios where a label is more performant than a property (namely filtering after traversing a link), though the scenario I suggested is apparently worse according to this old article:

https://graphaware.com/neo4j/2015/01/16/neo4j-graph-model-design-labels-versus-indexed-properties.html

Regardless of performance, locking down the classes to match label sets exactly makes it so that `Neomodel` cannot describe an arbitrary Neo4j database, but rather only ones which use labels in the restricted way. I suppose that is a valid position to take but when I pick up a SQL ORM, for instance, I very much expect it to cover all of SQL's uses. It's also a frustrating experience to start building and finding out a library you chose is restrictive when it could be permissive instead.

The prefix option you propose is certainly an interesting option, but it is annoying to have the prefixes on the labels when doing manual querying of the DB. Implementing that means a pretty hard version break too, as you'd need to run a migration on any existing DB to get the prefix on every node. Instead of the prefix, you could keep a set of all known neomodel labels and filter the query results before doing the class lookup to avoid the need for the prefix (but at the cost of doing slightly more processing).

Alternatively, one of my coworkers suggested modifying the model class to accept a list of optional labels and then enumerate over the options when creating the class map to include all the possibilities. Example:

```python
class BlogPost(StructuredNode):
      __label__ = "BlogPost"
      __optional_labels__ = ["Active", "TopTrending"]

      text = fields.StringProperty()


resulting_class_map = {
        frozenset({"BlogPost"}): BlogPost,
        frozenset({"BlogPost", "Active"}): BlogPost,
        frozenset({"BlogPost", "TopTrending"}): BlogPost,
        frozenset({"BlogPost", "Active", "TopTrending"}): BlogPost,
}

```

I think this is better than having `neomodel` ignore extra labels completely. This option also gives more strength to the model, which seems to be your desire.

What do you think of something like that?

**Comment by henryfjordan** [comment]
Another one of my coworkers came up with the following scenario:

I start writing an application with the following code:
```python
class Base(StructuredNode):
        created_at = DateTimeProperty()

class BlogPost(Base):
      text = fields.StringProperty()
```
which results in BlogPost nodes having the labels `[Base, BlogPost]`. 

Then, some time later, I learn about the `__abstract_node__` feature, or I just decide I didn't really want `Base` after all. With the current version of the the Object Resolution running, once I change the code I can no longer query for `BlogPost` without first running a migration like `MATCH (b:Base) REMOVE b:Base`. 

I feel like having some workaround for that scenario would be beneficial

**Comment by aanastasiou** [comment]
>Regardless of performance, locking down the classes to match label sets exactly makes it so that Neomodel cannot describe an arbitrary Neo4j database, but rather only ones which use labels in the restricted way. 

Correct. 

`neomodel` uses this convention of treating node labels as node types. Any existing database that does not follow this would take some effort to be accessed by it.

> ...when I pick up a SQL ORM, for instance, I very much expect it to cover all of SQL's uses.

So far as the underlying SQL respects conventions, yes.

 > It's also a frustrating experience to start building and finding out a library you chose is restrictive when it could be permissive instead.

[I agree](https://github.com/aanastasiou/neomodelInheritanceTest)

> ...it is annoying to have the prefixes on the labels when doing manual querying of the DB.
Maybe, but I wonder how much this inconvenience weighs versus its pay-off.

> Implementing that means a pretty hard version break too, as you'd need to run a migration on any existing DB to get the prefix on every node.

Indeed and this is something that `neomodel` needs. Because even if you were to make a simple change in your model right now, there is no migration tool that would run on the database to update it to reflect these changes. At the moment, this has to be handled manually.

1. > Instead of the prefix, you could keep a set of all known neomodel labels and filter the query results before doing the class lookup to avoid the need for the prefix (but at the cost of doing slightly more processing).

2. > Alternatively, one of my coworkers suggested modifying the model class to accept a list of optional labels and then enumerate over the options when creating the class map to include all the possibilities.

So, we do agree that the solution here is to have `neomodel` perform its resolution over a well defined set of lables but not exclude the possibility that there are other labels that might be applied to the nodes.

Out of these two proposals here, my reluctant vote would be for number 2 because it allows us to explicitly set which are these extra labels a Node might have that we would need to ignore during object resolution.

This extra step will introduce an additional delay. The logic now is:

1. Given a `Node` (from the neo4j Python driver) retrieve its labels
2. Create a set difference between the node's labels and the optional labels
3. Check that the remaining set of labels actually matches the optional labels (if not throw an exception)
4. Use the other part of the difference to perform object resolution as per the usual.

It is probably useful to mention here that when you are using object resolution on a plain `cypher_query`, it is applied recursively because some `Node` may have been returned as the element of some nested list.

So, this logic has to run on each and every `Node, Relationship` (and quite possibly elements of `Path`, soon).

How about this for a way forward? You guys create a PR along the lines of idea number 2 (from above) which also enables you to move ahead with your own work. Then we have a look at it, examine its performance and if there is consensus about its adoption we incorporate it to `neomodel`.

What do you think?


> Then, some time later, I learn about the `__abstract_node__` feature,

The `__abstract_node__` feature will be removed.

**Comment by henryfjordan** [comment]
I'll open a PR, but it will probably take until Monday or Tuesday.

Thanks for being flexible and going over this with me! I really appreciate how receptive you've been to making changes to fix this issue.

**Comment by aanastasiou** [comment]
@henryfjordan You are welcome, there is no rush.
