### ISSUE TITLE
Recursion depth exceeded when querying too many nodes

### ISSUE THREAD

**Issue by ThoreKr** [neo4j-contrib/neomodel#430]
After a couple of queries like
```Python
db.Person.nodes.get(name=partner['name'])
```
I get a larger traceback as in the example below
```
   result = self._get(limit=2, lazy=lazy, **kwargs)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib/python3.6/site-packages/neomodel/match.py", line 539, in _get
    self.filter(**kwargs)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib/python3.6/site-packages/neomodel/match.py", line 628, in filter
    self.q_filters = Q(self.q_filters & Q(*args, **kwargs))
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib/python3.6/site-packages/neomodel/match_q.py", line 193, in __and__
    return self._combine(other, self.AND)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib/python3.6/site-packages/neomodel/match_q.py", line 181, in _combine
    return copy.deepcopy(other)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib/python3.6/site-packages/neomodel/match_q.py", line 80, in __deepcopy__
    obj.children = copy.deepcopy(self.children, memodict)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/thore/.local/share/virtualenvs/flscrape-5IkkNlD1/lib64/python3.6/copy.py", line 150, in deepcopy
...
RecursionError: maximum recursion depth exceeded
```

A way to cope with this is to set the maximum recursion depth to something larger then 10k. Then I only get `terminated by signal SIGSEGV (Address boundary error)`

**Comment by aanastasiou** [comment]
@ThoreKr Thanks for raising this as a potential issue but it would be best if it was accompanied with a bit more information about:

1. The structure of your data model (if possible)
2. Anything else that may be hapenning around the `.get()` ?

By the way, are you sure that is `db.Person` and not just `Person.nodes....` ?

**Comment by ThoreKr** [comment]
@aanastasiou sure thing
The database model is pretty small and close to the sample
```Python
class Partnership(StructuredRel):
    relationshipType = StringProperty()
    since = DateTimeProperty(
        default=lambda: datetime.now(pytz.utc)
    )


class Country(StructuredNode):
    name = StringProperty(unique_index=True, required=True)

    # traverse incoming IS_FROM relation, inflate to Person objects
    inhabitant = RelationshipFrom('Person', 'IS_FROM')


class Region(StructuredNode):
    name = StringProperty(unique_index=True, required=True)

    # traverse incoming IS_FROM relation, inflate to Person objects
    inhabitant = RelationshipFrom('Person', 'IS_FROM')


class Interest(StructuredNode):
    name = StringProperty(unique_index=True, required=True)

    # map incoming relationships
    interestedPerson = RelationshipFrom('Person', 'IS_INTERESTED_IN')


class Group(StructuredNode):
    name = StringProperty(unique_index=True, required=True)

    # map incoming group member relationships
    member = RelationshipFrom('Person', 'IS_MEMBER')


class Person(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(unique_index=True)
    age = IntegerProperty(index=True, default=0)
    sex = StringProperty()
    orientation = StringProperty()
    url = StringProperty()

    # traverse outgoing IS_FROM relations, inflate to Country objects
    country = RelationshipTo(Country, 'IS_FROM')
    region = RelationshipTo(Region, 'IS_FROM')
    interest = RelationshipTo(Interest, 'IS_INTERESTED_IN')
    group = RelationshipTo('Group', 'IS_MEMBER')
    partner = RelationshipTo('Person', 'PARTNER_WITH', model=Partnership)
```
The model is outsourced to another file and the module imported as db, so that's why it's model.db

Currently I'm trying to add more persons, so there is an iteration over all users:
```Python
for user in db.Person.nodes.all():
    logging.info(user)
    data = getDict(user)
    addPartners(user, data.setdefault('partners', list()))
```

And `addPartners()` always crashes at:

```Python
def addPartners(person, partners):
    logging.info(partners)
    for partner in partners:
        logging.info(partner['name'])
        try:
            logging.info('Try to find person')
            partnerNode = db.Person.nodes.get(name=partner['name'])
            logging.info('Found person')
        except db.Person.DoesNotExist:
            logging.info('Creating new user')
```
After a couple of runs (python without increased recursion limit 3), with a max recursion of 10000 30 nodes and with more after 31 nodes the kernel-side memory issues occur.

**Comment by aanastasiou** [comment]
@ThoreKr Thank you, that was quick :)

> The database model is pretty small and close to the sample
...which sample would that be?

This...
```
class Country(StructuredNode):
    name = StringProperty(unique_index=True, required=True)
    # traverse incoming IS_FROM relation, inflate to Person objects
    inhabitant = RelationshipFrom('Person', 'IS_FROM')

# . . .

class Person(StructuredNode):
    uid = UniqueIdProperty()
    name = StringProperty(unique_index=True)
    age = IntegerProperty(index=True, default=0)
    sex = StringProperty()
    orientation = StringProperty()
    url = StringProperty()

    # traverse outgoing IS_FROM relations, inflate to Country objects
    country = RelationshipTo(Country, 'IS_FROM')
    region = RelationshipTo(Region, 'IS_FROM')
    interest = RelationshipTo(Interest, 'IS_INTERESTED_IN')
    group = RelationshipTo('Group', 'IS_MEMBER')
    partner = RelationshipTo('Person', 'PARTNER_WITH', model=Partnership)
```

...is what is probably creating the problem. Specifically, the fact that `Person` points to `Country` and `Country` points back to `Person`. Please **do not** add reciprocal directed edges when you want to denote an undirected relationship.

If you want either entities to be reachable by the other (i.e. be abel to answer both: *"Who lives in a given Country"* and *"Which countries does a given Person live in?"* (Which is already a bit "odd" as a question)) then you only need to add **one** relationship that is undirected. This can be done in one of many ways but to keep things as clear as possible, you might want to add the relationship **only** to the `Person` "side". If you add a `neomodel.Relationship` then the relationship will be undirected. When you query your data on the neo4 browser, you might see arrows pointing towards some direction but that does not denote a constrain. If you establish a `neomodel.Relationship` (again, an **undirected** relationship) you will then be able to query it in either way, for example: `(:Person)-->(:Country)` as well as `(:Person)<--(:Country)`.

If you were to further specify a `neomodel.RelationshipTo` (or `...From`), then you would still be able to run both queries as above (neo4j is not going to complain) but only one of those queries will return data (the one that is matching the direction of the relationship).


> The model is outsourced to another file and the module imported as db, so that's why it's `db.Person`
Since `neomodel` also has a `neomodel.db` object, I would suggest that you change that to something a bit more distinct to avoid confusion. Just a suggestion.

> ...there is an iteration over all users

OK, it is not exactly clear what is hapenning around those snippets but you are already going in a round about way in creating those entities.

So, in no particular order, here is a brief list of things to check:

1. Try to ensure that you don't have any self-loops (`Person` is their own `Partner`).
2. If you already have the "relationship" data, then you don't have to re-query everything. The usual way to go about this is to first create the `Person` nodes (which is one iteration) and **then** establish the relationships (which, once you have established all `Person`s, is again, another iteration). In this way, you will be able to use `neomodel`'s [`StructuredNode.get_or_create`](https://neomodel.readthedocs.io/en/latest/batch.html#get-or-create) and if you "drape" that in a [transaction](https://neomodel.readthedocs.io/en/latest/transactions.html), it will be the fastest option for importing your data in the database via neomodel. In addition, if you "unfold" your graph's creation in this way you can do the import in two separate transactions. The `try/catch` bit is fine and readable but for large amounts of data it is slow.

What is `.setdefault` on `data`? Is that one of your objects or is `data` coming from another library?

Hope this helps.

**Comment by ThoreKr** [comment]
@aanastasiou Thank you for the quick and extensive reply

>> The database model is pretty small and close to the sample

> ...which sample would that be?

https://neomodel.readthedocs.io/en/latest/getting_started.html#definition
In the getting started the relations were mentioned in both ways.

> What is .setdefault on data? Is that one of your objects or is data coming from another library?

`data` is provided by a webcrawler. It is a dictionary with a couple of arrays (one of them being partners). In case no partners were defined by the crawling logic it uses setdefault providing an empty list.

Sorry for providing not more context, the intention of this loop is to add more nodes to the database by crawling existing users again to obtain their partners and create them as well (if they don't already exist). I wanted to avoid using `get_or_create()` in that case because the create logic is outsourced and takes care of the dependencies as well (setting all values and creating groups and interests).



> Please do not add reciprocal directed edges when you want to denote an undirected relationship.

Regarding self-loops, may it be an issue that I have relationships between to Persons (directed, one in each direction) but with different attributes? I have dropped the database and tried to reinitialize with some tweaks avoiding this but it still crashes almost immediately (Processing only one person)

**Comment by aanastasiou** [comment]
@ThoreKr No worries, hope it was helpful.

> In the getting started ...

I see. We need to revise a few questions of the documentation as evident by the 'documentation` tag in the [issue](https://github.com/neo4j-contrib/neomodel/issues) list.

> ...the intention of this loop is to add more nodes to the database by crawling existing users again to obtain their partners and create them as well...

From my experience with working with `neomodel` and ETL tasks, I can confidently say that this approach is slow and is trying to achieve many objectives at the same time. I would suggest that you first do everything you need to do to get the "data" before you hit the "data entry" task. In this case, I would try to crawl the "web of users" (whether in one or multiple passes) and send the result of that operation to the "data entry" task. In this way you can optimise either independently of each other.

> ...the create logic is outsourced...

I don't think I fully understand this (you mean deferred, to another routine / program?). In my experience, I have concluded to a pattern where, given a graph to be uploaded to the database, I will first establish all Nodes and then all Relationships. Sometimes, this is as messy as it can get because the de-duplication (or indexing) falls on you (rather than relying on the db indices as you hint at doing here) but it is the faster and I would dare say "cleaner" option in the long term.

> Regarding self-loops, may it be an issue that I have relationships between to Persons (directed, one in each direction) but with different attributes?...

I do not see how this, on its own, would cause any problems. As far as I can tell, this does not sound like a `neomodel` problem. Self-loops can definitely be problematic if you are not prepared for them but failing with just one node is "odd". 

A great aid in debugging for me, has been to export a given network in `.dot` (or whatever [`graphviz`](https://github.com/graphp/graphviz) calls its format these days) and then use `graphviz` to check the validity of the data "by hand". You might find [`Networkx`](https://networkx.github.io/) useful in this case, just for the graph handling and easy serialisation to a format that can be used by other software.

If you are sure that the network (primary data) is alright then you can proceed with debugging data model / querying problems.

All the best

P.S. Would you consider this issue answered? Shall we close it?

**Comment by ThoreKr** [comment]
@aanastasiou First of all - thank so much for all the input and the extensive replies.

I've managed trace down the issue to the evaluation of one specific node and debug that one further until I stumbled about two things:
1. At some point I put an array in place of a string as I wanted to get a node (`Person.nodes.get(name=<Array>)`) which caused the same deepcopy recursion error.
2. When taking a look into the python debugger tracing the variable on this certain node which caused the get to fail mouseover on the type (using vscode) said `NavigableString` - which was rather confusing. But a `str()` around it fixed it.

So `NavigableString` is something returned by BeatifulSoup. I haven't found out yet why the type differed in that case - but that's another issue.

So from my side this issue can be closed. One may ask the question whether this issue should be caught earlier by checking whether the argument has a valid type. Though I'm not sure this is going to work out since there might be other types as well (?).

Again - thanks for all the help and input - I'm going to revise the ETL process.

**Comment by aanastasiou** [comment]
@ThoreKr No worries, you are welcome.

This particular behaviour is related to [this](https://github.com/neo4j-contrib/neomodel/issues/429) issue.
(And possibly one more issue that I am trying to figure out its impact at the moment before mentioning it here).

At the moment, the best strategy for use case scenarios such as yours, is to cast to `str` indeed.

All the best
