### ISSUE TITLE
Possibility of onupdate argument

### ISSUE THREAD

**Issue by Moro-Code** [neo4j-contrib/neomodel#435]
Wondering if its possible to add an onupdate argument to parameters where a function can be defined to run when a node is updated.  i.e.

``` python
class Person(StructuredNode):
      .... Other fields
      updatedOn = DateTimeProperty(default_now=True, onupdate = lambda: datetime.utcnow() )
```
I know similar behavior is possible by specifying a pre_save hook however it would be awesome if this could be done directly on the property.

**Comment by aanastasiou** [comment]
@Moro-Code As this is a feature request, do you think you could provide a more use-case based description? It sounds like this is very specific to this particular thing of storing the date of updating the node. It could also be useful for properties whose value is the result of other properties **and** have to be stored too (again, very, very, very specific use case).

In all of these cases, it is better to handle the "update" explicitly rather than automatically.

**Comment by Moro-Code** [comment]
Yup it's very specific to the DateTimeProperty

currently I am doing the following 

```python
class Survey(StructuredNode)
     surveyId = UniqueIdProperty()
     addedOn = DateTimeProperty(default_now=True)
     updatedOn = DateTimePropery(default_now=True)
    def pre_save(self):
        self.updatedOn = datetime.utcnow()
````
This works but when for example I would create a new node the addedOn and updatedOn would be different by a few milliseconds.

**Comment by aanastasiou** [comment]
@Moro-Code Indeed.

Notice however that this is not something that could be "remedied" by an `onupdate()`, any better than it can be handled by the `pre_save()`.

The "properties" are created for each attribute of a `StructuredNode` subclass at runtime and "examined" in an iteration as required by subsequent operations. Therefore, the only way for the timing to be the same in those two properties is to first "save" it and then assign it to each property separately.

Catching that particular use case per Node would be too specific for `neomodel` I think.

All the best
