### ISSUE TITLE
object states and session 

### ISSUE THREAD

**Issue by Moro-Code** [neo4j-contrib/neomodel#436]
Not sure if this is a decision that has been taken in the past. Couldn't really find anything in the issues or the docs.

Wondering whether it would be worth considering implementing object states relative to a session similar to [SQLAlchemy](https://docs.sqlalchemy.org/en/13/orm/session_state_management.html) . Instead of conducting an operation for example by calling the save, delete, refresh ect on the individual objects it would be conducted by the session which is managing the state of the objects relative to the tracked transactions with the database.

- I find this makes handling session's and transactions syntactically easier instead of using the transaction decorator or in a with block 
- Ensures that objects are consistent across the application
- Provides more fine grain control to the session
- you are able to use the normal constructor, add objects to the session then commit them all at once

Apologies if my terminology is not too correct I am very new to neomodel

**Comment by aanastasiou** [comment]
@Moro-Code I think that I understand what you are suggesting but just to make sure, can you provide a more descriptive example?

Until then, please note that there are certain design and technical reasons that dictate the way actions are taken on the objects. The "equivalent" of what you suggest in `neomodel` is to put a whole section of operations in an [explicit transaction](https://neomodel.readthedocs.io/en/latest/transactions.html#explicit-transactions).

Hope this helps.

**Comment by Moro-Code** [comment]
@aanastasiou Thanks for getting back! Think I just have to wrap my head around how transactions are handled here to what I'm used to. Here is a code example to the behavior I'm suggesting 

``` python
class Person(StructuredNode):
      personId = UniqueId()
      name = StringProperty()
      # other fields
new_person = Person(name="blah")
# instead of
new_person.save()
# create a session object
# the session object would be created by a session factory which also acts as a registry 
# https://martinfowler.com/eaaCatalog/registry.html
# if there is a current session in the registry as relates to the thread then that will be returned
# if there is no session, a new session object will be created and returned 
new_sess = Session()
new_sess.add(new_person)
# more operations adding more objects into the session, deleting ect

# commit tracked changes to the database 
new_sess.commit()
```
A neomodel object would have different states as relates to a session 
- before being added into a session it is transient
- when added to a session it is pending
- when pushed to the database it is persistent
- if it is deleted it's state is deleted
- when the deletion is committed it, the object moves to the detached state

Because the session is in a registry, I am able to call the same session anywhere from the application and thus also have the data access objects and their states consistent across the entire application. Let me know if this is clear enough.

Thank you for your time :)

**Comment by aanastasiou** [comment]
@Moro-Code No worries.

> I just have to wrap my head around how transactions are handled here to what I'm used to

Indeed. In terms of performance, starting a transaction with the neo4j server and sending it queries is definitely faster than doing it in "atomic" operations. So, creating 100 nodes in this way: `[SomeNode(some_attribute="Some_Value").save() for k in range(0,100)]` is slower than:

```
with neomodel.db.transaction:
    [SomeNode(some_attribute.......
```

The "registry" idea is valid but cannot be implemented in `neomodel` without heavy modifications. The plan is to be able to offer [something like this](https://github.com/neo4j-contrib/neomodel/wiki/TODOs-&-Enhancements#implement--revamp-batch-operations-potentially-asynchronous) in a future iteration.

I say "something like this" because, again, the way the API would work would have to follow the capabilities exposed by the server. In Neo4j, there is the concept of a ["unit of work"](https://neo4j.com/docs/api/python-driver/current/transactions.html). Basically, operations within the same transaction are guaranteed integrity but that does not mean that two operations happening in two parallel sessions cannot raise an exception (e.g. for uniqueness). In other words, this "registry" would have to do a lot of high level work to ensure that there are no redundant or conflicting operations about to be sent to the database. If it did not then there would have to be a lot of work of sorting out which exceptions are "expected" and "genuine".

All the best

**Comment by Moro-Code** [comment]
Thank you for taking the time to respond, really appreciate it. So far I love the simplicity of the tool and one of the main reasons I decided to switch to Neo4j.

This makes a lot of sense and am excited to see neomodel evolve. Would love to contribute in any way I can

**Comment by aanastasiou** [comment]
@Moro-Code You are welcome, I am sure everyone of the ~30 developers who have contributed to `neomodel` is happy to hear to that too.

> Would love to contribute in any way I can
Well, apart from bugs and various improvements here and there, we recently started working on [a number of things we could be working on](https://github.com/neo4j-contrib/neomodel/wiki/TODOs-&-Enhancements) based on the list of issues. Some of them of course require very big changes but others are easier to be done. Depending on your interests too, pick anything that you fancy from that list and just give it a go :)

The other thing that is of relatively high priority, is the transition to a Python 3.0 only version. A couple of users have been working towards that already (see [here](https://github.com/neo4j-contrib/neomodel/pull/315) for example). That is another relatively straightforward thing because it involves "ripping apart" code that would be redundant in a Python 3.0 only environment.

All the best
