### ISSUE TITLE
Filtering on SemiStructuredNode only on defined properties

### ISSUE THREAD

**Issue by Moro-Code** [neo4j-contrib/neomodel#449]
If ad-hoc fields can be added to a node when it is defined as a SemiStructuredNode shouldn't there be the ability to filter nodes based on these fields?

For example say we have the following simple model

``` python
class SomeModel(SemiStructuredNode):
    some_field = StringProperty()
```

I then create a node and add some ad-hoc fields

```python
node = SomeModel()
node.some_other_field = "blah blah"
node.save()
```

If somewhere later I try to get this node

```python
node = SomeModel.nodes.get( some_other_field="blah blah")
```
I will get a ValueError: no such some_other_field on SomeModel

So how can you get nodes based on ad-hoc fields without having to do a cypher query and then inflating the objects?

**Comment by aanastasiou** [comment]
@Moro-Code Alright, let me have a quick look at these too queries regarding `SemiStructured` nodes and get back to you please.

**Comment by Moro-Code** [comment]
Yup no problem! Appreciate all the effort and sorry for spamming issues

**Comment by aanastasiou** [comment]
@Moro-Code I can confirm that this is the intended behaviour. The reason for this failure is that depending on the type of the property, it might be necessary to take some actions on the `Property` object itself (see [here](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/match.py#L145)).

Is it possible to describe your use case in a little bit more detail to see if this could make it into our [feature list](https://github.com/neo4j-contrib/neomodel/wiki/TODOs-&-Enhancements)? Or, maybe we could see an alternative way of achieving it (?).

For the moment, I am afraid that you are stuck with "manual" querying.

**Comment by Moro-Code** [comment]
Yes of course. Basically I'm building a survey tool. I would like users to be able to attach metadata to surveys and questions such as notes, tags ect... I have an API from which users are able to get and filter their survey data based on the information so it would be awesome if there was a way to use filtering methods to be able to do this rather than creating a cypher query and  then inflating objects. I could just use optional fields but I can't anticipate all the fields that the user will want

**Comment by aanastasiou** [comment]
@Moro-Code ok...

1. Since you are thinking along the lines of `.get()`, I suppose that you are thinking about a middle layer that translates the user's "wish" to an internal query. Maybe your own little Domain Specific Language, as simple (or complicated) you want that to be.

2. The use case you mention does not seem to have a need for complex data types (or validation, beyond perhaps sanitation of input) and the query does not seem to want to extend beyond the properties of a single node and the tags do not seem to have some sort of hierarchy.

Therefore, it might be better to model these additional properties as `SurveyProperty` nodes. Then each `Survey` would maintain a "link" to zero or more of those properties.

In this way, your DSL will only be translating user "wishes" to internal queries over `SurveyProperty` nodes, rather than ad-hoc properties attached to the "data bearing" nodes.

What do you think?

**Comment by Moro-Code** [comment]
This sounds like a good way to do it and what I was thinking of doing anyways. I guess I was just trying to be lazy and dumping properties in the data bearing nodes. It would be useful though to have a way to filter based on fields added that were not initially defined in the SemiStructuredNode

**Comment by aanastasiou** [comment]
@Moro-Code The unknown in that case would be the "type" of the property in order to perform validation.

You could add a `.get()` to `SemiStructuredNode` that runs a `.cypher()` and returns `NodeSet` but assumes that any extra properties are just `StringProperty`. 

But that would be more of a convenience function for querying rather than something that ensures that data is stored exactly as intended.
