### ISSUE TITLE
how to paginate a query?

### ISSUE THREAD

**Issue by Otoru** [neo4j-contrib/neomodel#459]
Writing a query manually, I use the skip and limit parameters to do pagination.
how to do this with ogm?

**Comment by aanastasiou** [comment]
@Otoru In exactly the same way but when you return whole nodes ([and hopefully soon relationships too](https://github.com/neo4j-contrib/neomodel/pull/421)), neomodel will handle the type marshalling for you.

For example:

```
r = db.cypher_query("MATCH (a:Person)-[:KNOWS]->(b:Person) WHERE a.name='Tony Hawk' RETURN b", resolve_objects = True)
```

`r` is now a list of entities and it will contain properly instantiated models from your application's data model, that correspond to the ``Person`` entity.

Hope this helps (?)

**Comment by Otoru** [comment]
Thanks for the feedback, but I was thinking of something related to OGM.

When doing something like `Person.nodes.all()` it would be interesting to be able to work with parameters similar to `skip` and `offset`.

**Comment by aanastasiou** [comment]
Hi @Otoru 

The short answer is that this cannot be done with the current version of neomodel.

The longer answer is that what you mention is more reasonable to be implemented at the level of the application code, rather than ``neomodel``.

Neomodel expressions that translate to cypher queries "communicate" via [NodeSet](https://github.com/neo4j-contrib/neomodel/blob/b843417bc9aa0568fc0612caa90597bff41d603e/neomodel/match.py#L513) objects.

When you say `something.all()` what you get back from that function is a ``NodeSet`` which in turn can be used to filter its results and return another intermediate ``NodeSet`` which makes it possible to filter its results and so on.

What allows you to do pagination are the [SKIP](https://neo4j.com/docs/cypher-manual/current/clauses/skip/) and [LIMIT](https://neo4j.com/docs/cypher-manual/current/clauses/limit/) clauses and they always appear at the body of a [RETURN](https://neo4j.com/docs/cypher-manual/current/clauses/return/) (In terms of syntax, see ``oC_ReturnBody`` which is the only clause that contains ``oC_Skip`` or ``oC_Limit`` in [cypher's grammar specification](https://www.opencypher.org/resources)).

This makes the addition of ``skip`` and ``limit`` parameters at the level of ``NodeSet`` difficult. It would have to somehow be guaranteed that they are included at the last occurring ``NodeSet``, or raise an exception if they happened to occur twice within a query or (perhaps worse of all) the skip and limit are applied client side (on the ``NodeSet`` results) but then start causing logical errors because two where used in a query and the first produced zero results for the subsequent ones to paginate.

It is with these difficulties in mind that I suggest that this is better to be handled at the application level.

In terms of alternatives, [Pypher](https://github.com/emehrkay/Pypher) does some really clever abstraction between Python and Cypher by essentially allowing you to construct Cypher queries with Python function composition.

So, you can still construct "programmable" and testable queries (even generic parts that can be further composed if you like) and then pass them over to ``neomodel`` for execution.

Hope this helps but let me know if there is anything else we can do (?).

All the best
