### ISSUE TITLE
Save doesn't work

### ISSUE THREAD

**Issue by nrgx** [neo4j-contrib/neomodel#463]
I've set up User model that inherits StructuredNode, so filling up some data and firing up save() method doesn't do anything. In my settings file I set db_connection to my bolt url with auth credentials. Django and Neo4j are dockerized, so I've set up networks, links and depends_on clauses in docker-compose.yml file installed labels in Django container and everything works, so that's not docker issue.

**Comment by antipyrrhus** [comment]
Have you made sure that the neo4j database is up and running, and that you can use e.g. cypher queries from within the neo4j browser to create new nodes? If so, have you experienced problems with neomodel functions in general, or is it solely the save method that doesn't seem to work? I'm guessing there's something awry with the setup because save() literally executes a cypher query, so if the database is working and neomodel is properly connected to it, there's no reason the method shouldn't work.

**Comment by nrgx** [comment]
As I wrote, yes Neo4j is up and running and Django container won't get up, if Neo4j's container didn't as it depends on it. Well, I wrote some cypher query from browser which created empty node, bc I didn't provide any attributes. But then I wrote a cypher query from manage.py shell and run it with `cypher_query` function from neomodel's `db`, and it worked. The cypher query: `CREATE (u:User {phone: '88005553535', email:'engineer@gmail.com', first_name:'Alibek', last_name:'Kaparov'})`. Then created node was in the Neo4j browser. Also, there is another function from `StructuredNode` called `create`, which also doesn't work.

**Comment by antipyrrhus** [comment]
OK, could you provide the part of your code in which you attempted to call save() and create(), along with the corresponding node classes you've created?

**Comment by nrgx** [comment]
My User node class. Actually it was re-written from Django's model.Model. Some parameters are from old records, but I don't thinks that's the problem, it could throw an exception if I do something wrong, isn't it? But still no errors were raised and empty list was returned. 
```
class User(StructuredNode):
    id = UniqueIdProperty()
    phone = StringProperty(
        max_length=20,
    )
    email = EmailProperty(
        max_length=255,
        blank=True,
        null=True,
        unique=True,
    )
    first_name = StringProperty(
        max_length=100,
    )
    last_name = StringProperty(
        max_length=100,
    )
    middle_name = StringProperty(
        max_length=100,
        blank=True,
        null=True,
    )
    created_at = DateTimeProperty(
        default_now=True
    )
    updated_at = DateTimeProperty()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def full_name(self):
        if self.middle_name:
            return f"{self.first_name} {self.last_name} {self.middle_name}"
        return str(self)
```
The code.
With save: 
`User(phone='88005553535', email='engineer@gmail.com', first_name='Alibek', last_name='Kaparov').save()`
With create 
`User.create(phone='88005553535', email='engineer@gmail.com', first_name='Alibek', last_name='Kaparov')`

**Comment by antipyrrhus** [comment]
Alright, it seems to me that the crux of the issue is that you need to replace the line:
`id = UniqueIdProperty()`
with something similar to:
`uid = UniqueIdProperty()`
This is because `id` is a built-in variable in neo4j/neomodel and is automatically assigned a number upon initial creation, so it's causing problems when you override it. (I think it might be a good idea for neomodel to explicitly warn you of this though)

You don't need to remove all parameters like you did in your edit. However, parameters `blank`, `null`, `unique` are not used in neomodel afaik. You can use `default` and `unique_index` instead if you like. See [here](https://neomodel.readthedocs.io/en/latest/module_documentation.html#neomodel.properties.Property) for more info on parameters.

**Comment by nrgx** [comment]
Thanks, mate. It worked. Renamed all classes' ids to uids.
