### ISSUE TITLE
[Generic Question] Best Practice

### ISSUE THREAD

**Issue by shawnngtq** [neo4j-contrib/neomodel#548]
### When do you use neomodel OGM, cypher query or neo4j-python-driver?

In terms of defining schema, I think neomodel OGM is the best as it best resemble Django's models.

In terms of database querying, which of them would have the best performance? I think OGM would have the worst performance since there's overhead to convert model methods into cypher query? 

neo4j-python-driver > neomodel `cypher_query` > neomodel OGM?

What are the clear cut situations where you should use certain method over the other?

### Async requests

Are async requests supported? If they are, where can I find out more about it?

**Comment by SimaDovakin** [comment]
@shawnngtq I think, `neomodel` doesn't support asynchronous requests to the database. I simply tried to find `async def` in the repo and I didn't find any async functions.

**Comment by aanastasiou** [comment]
In no particular order:

1. **Async requests:** This is not just about supporting async access at the OGM level, but all the way to the DBMS level. Async working is still possible (e.g. you can embed neomodel calls into async functions to query the database) but you have to understand the pros and cons at the DBMS level. At the very least, you would have to [wrap your call in a transaction](https://neomodel.readthedocs.io/en/latest/transactions.html). But having done this, you would have to understand that transactions are processed separately and "atomically". This means that the DBMS state that the two calls would "see" might be different and this is not something that `neomodel` enforces but it is enforced at the DBMS level.

2. **When do you use `neomodel`? **: When you have a data model that relies heavily on inheritance to define its entities and relationships.

3. **When do you use `cypher_query`?**: I suppose that you mean [`db.cypher_query()`](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/util.py#L276). This is the call that all queries rely on ultimately, whether they are "constructed" or directly applied to the database. The short answer is to use `cypher_query()` when you have a query that cannot be expressed with [one of the other mechanisms](https://neomodel.readthedocs.io/en/latest/queries.html) that are built-in to `neomodel`. Whenever possible, you should try to express your queries, using the neomodel API because its [query construction is "lazy"](https://en.wikipedia.org/wiki/Lazy_evaluation) and you can chain together operators to express all sorts of different queries. But, although neomodel has a very rich query repertoir (and is about to get even better with an upcoming release), there still might be cases where you have to resort to a "raw" CYPHER query. In that case, you should use `cypher_query()`. But, even in that case, `cypher_query()` gives you some benefits "for free", such as, the option to perform data marshalling for data types described using neomodel. For more information see ["Automatic class resolution"](https://neomodel.readthedocs.io/en/latest/extending.html?highlight=resolution#automatic-class-resolution) in the docs.

4. **When do you use `neo4j-python-driver`?**:  *Almost* never.  Let me explain: `neomodel` is relying on the Python driver for its communication with the DBMS and the code is making every possible effort to automate repetitive tasks that you would have to do again and again if you based your code on the python driver directly. Therefore, unless you are trying to do something that **has the need to talk to the DBMS at a very low level**, then you do not really have a use for the python driver. Another point where you **might** need to understand at least the data types of the python driver, is when `cypher_query()` returns its results in "raw" python driver objects. But getting to grips with this [is extremely straightforward](https://neo4j.com/docs/python-manual/current/data-types/).

5. *" I think OGM would have the worst performance since there's overhead to convert model methods into cypher query?"*: Well, think twice about it. While it is true that queries first have to be constructed and then executed and this should take more time, `neomodel` performance is not the bottleneck. The way the queries are constructed is straightforward, to the extent that you "execute what you specify". In other words, `neomodel` itself does not attempt to optimise a query. It provides constructs that allow you to build queries in an intuitive way that **respect the constraints of the database schema**. All this is basically boiling down to is piecing together a string (the query) which is then sent to the database. Additionally, as Python's performance gets better, the actual query construction stage gets better too. I will keep in mind to profile some of the code I am using (that contains fairly long queries) to report back exact numbers, but I do not see these numbers climbing about to ms order of magnitude. 

What are your performance requirements? What sort of application are you putting together that makes you worry about the performance of neomodel?

**Comment by shawnngtq** [comment]
Thanks for the detail write up!

No specific requirements, just wanted to hear best practices back in 2021.

The performance part is a personal preference, since Python is already slower than other languages such as golang / rust, would like to avoid as much overhead as possible.

**Comment by aanastasiou** [comment]
@shawnngtq Glad to hear that, sorry it took some time for the response. If you feel this question has been answered then we can close it (?)
